add non container formats flac wavpack and wav.
hiveeyes/saraswati pull request #15
Opened 2021-07-22 22:28 UTC by MKO1640

2021-07-22 22:36 UTC, amotl requested changes
Hi Michael,

thanks a stack for this excellent contribution. I just added some minor comments about "naming things". Thank you in advance for addressing them.

With kind regards,
Andreas.

2021-07-22 22:36 UTC, amotl commented on saraswati/cli.py
>  )
Let's just call this "`--audio-format`"?

```suggestion
audio_format_opt = click.option(
    "--audio-format",
    "-af",
    "audio_format",
    envvar="AUDIO_FORMAT",
    type=click.Choice(["flac", "wav", "wavpack"]),
    default="flac",
    help="""Set audio format. Use either "flac" (default), "wav" or "wavpack".""",
)
```

2021-07-22 22:36 UTC, amotl commented on saraswati/recorder.py
> +
I believe this variable is not used at all?

```suggestion
```

2021-07-22 22:36 UTC, amotl commented on saraswati/setup/systemd/saraswati.default
> +# SARASWATI_CODEC_FORMAT=wavpack
```suggestion
# Configure audio recording format. default=flac
# SARASWATI_AUDIO_FORMAT=flac
# SARASWATI_AUDIO_FORMAT=wav
# SARASWATI_AUDIO_FORMAT=wavpack
```

2021-07-22 22:41 UTC, amotl commented on saraswati/cli.py
> +    codec_format: str,
```suggestion
    audio_format: str,
```

2021-07-22 22:41 UTC, amotl commented on saraswati/cli.py
> +        codec_format=codec_format,
```suggestion
        audio_format=audio_format,
```

2021-07-22 22:41 UTC, amotl commented on saraswati/model.py
> +    codec_format: str = "flac"          # flac,wav,wavpack
```suggestion
    audio_format: str = "flac"          # flac,wav,wavpack
```

2021-07-22 23:02 UTC, MKO1640 commented
Madness your speed borders on magic.
I'm just busy with something else but will then check it out extensively.
With kind regards,
Michael.

2021-07-23 03:22 UTC, MKO1640 commented
Quick test with all format options:
wav         = checked
flac          = checked
wavpack = checked
flac+ogg = checked
waw+ogg = checked
flac+mka = checked
waw+mka = checked
wavpack+ogg = broken - gst_parse_error: Delayed linking failed. (7) (./grammar.y(506): gst_parse_no_more_pads (): /GstPipeline:pipeline0/GstWavpackEnc:wavpackenc0
wavpac+mka = broken - failed delayed linking some pad of GstWavpackEnc named wavpackenc0 to pad  audio_%u of GstSplitMuxSink named muxer

Status : I go back to the drawing board

2021-07-23 11:28 UTC, amotl commented
Excellent! Don't worry about WavPack+container, it just doesn't work so we will have to investigate and/or ask upstream, see #7.

On 23 July 2021 05:22:13 CEST, MKO1640 ***@***.***> wrote:
>Quick test with all format options:
>wav         = checked
>flac          = checked
>wavpack = checked
>flac+ogg = checked
>waw+ogg = checked
>flac+mka = checked
>waw+mka = checked
>wavpack+ogg = broken - gst_parse_error: Delayed linking failed. (7)
>(./grammar.y(506): gst_parse_no_more_pads ():
>/GstPipeline:pipeline0/GstWavpackEnc:wavpackenc0
>wavpac+mka = broken - failed delayed linking some pad of GstWavpackEnc
>named wavpackenc0 to pad  audio_%u of GstSplitMuxSink named muxer
>
>Status : I go back to the drawing board
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hiveeyes/saraswati/pull/15#issuecomment-885372292

-- 
Sent from my mind. This might have been typed on a mobile device, so please excuse my brevity.

2021-07-23 15:37 UTC, MKO1640 commented
Okay, thats a pity. Despite an intensive search, I have also not found a solution.
I learned a lot about gstreamer while searching for myself, which is also good.
Do I still have to do something on my side?
I've added a few forgotten commits.

best regards
Michael

2021-07-23 17:16 UTC, amotl commented
Hi again,

I believe the patch is fine. I will squash all commits into a single one and issue a new release after integrating it.

Cheers,
Andreas.

On 23 July 2021 17:37:52 CEST, MKO1640 ***@***.***> wrote:
>Okay, thats a pity. Despite an intensive search, I have also not found
>a solution.
>I learned a lot about gstreamer while searching for myself, which is
>also good.
>Do I still have to do something on my side?
>I've added a few forgotten commits.
>
>best regards
>Michael
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hiveeyes/saraswati/pull/15#issuecomment-885725067

-- 
Sent from my mind. This might have been typed on a mobile device, so please excuse my brevity.

2021-07-24 22:13 UTC, amotl approved these changes

2021-07-24 22:14 UTC, merged